# Generated by Django 4.2.5 on 2023-09-26 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_date', models.DateField(verbose_name='Contest Date')),
            ],
        ),
        migrations.CreateModel(
            name='Pintxo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.contest')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taste_vote', models.CharField(choices=[('DL', "Didn't Like"), ('TS', 'Tasty'), ('VT', 'Very Tasty'), ('EX', 'Exceptional')], max_length=2)),
                ('presentation_vote', models.CharField(choices=[('DL', "Didn't Like"), ('WP', 'Well Presented'), ('VW', 'Very Well'), ('EX', 'Exceptional')], max_length=2)),
                ('originality_vote', models.CharField(choices=[('DL', "Didn't Like"), ('OR', 'Original'), ('VO', 'Very Original'), ('EX', 'Exceptional')], max_length=2)),
                ('pintxo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.pintxo')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
