version: "3.1"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    user: '0:0'
    container_name: pintxosDB
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Codice66
      MSSQL_PID: Developer
    volumes:
      - ./sqlserver-data:/var/opt/mssql