# Generated by Django 4.0 on 2021-12-28 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
        ('pintxos', '0003_pintxo_voted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pintxo',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='families.profile'),
        ),
        migrations.AlterField(
            model_name='pintxo',
            name='voted_by',
            field=models.ManyToManyField(related_name='voter', through='pintxos.PintxoVote', to='families.Profile'),
        ),
        migrations.AlterField(
            model_name='pintxovote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='families.profile'),
        ),
    ]
