name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies on main Project
      run: dotnet restore Pintxos/Pintxos.csproj
    - name: Build main Project
      run: dotnet build --no-restore Pintxos/Pintxos.csproj
    - name: Restore dependencies on Tests Project
      run: dotnet restore Pintxos.UnitTests/Pintxos.UnitTests.csproj
    - name: Build Test Project
      run: dotnet build --no-restore Pintxos.UnitTests/Pintxos.UnitTests.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal Pintxos.UnitTests/Pintxos.UnitTests.csproj
